/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    DarkToggleButton: typeof import('./src/components/slides/DarkToggleButton.vue')['default']
    Elk: typeof import('./src/components/icons/Elk.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GitHubLink: typeof import('./src/components/GitHubLink.vue')['default']
    ListDemos: typeof import('./src/components/ListDemos.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    ListProjects: typeof import('./src/components/ListProjects.vue')['default']
    Marker: typeof import('./src/components/slides/Marker.vue')['default']
    MarkerCore: typeof import('./src/components/slides/MarkerCore.vue')['default']
    MarkerPattern: typeof import('./src/components/slides/MarkerPattern.vue')['default']
    MarkerTips: typeof import('./src/components/slides/MarkerTips.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PicsPage: typeof import('./src/components/PicsPage.vue')['default']
    Plum: typeof import('./src/components/Plum.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slidev: typeof import('./src/components/icons/Slidev.vue')['default']
    SolidLogo: typeof import('./src/components/icons/SolidLogo.vue')['default']
    SponsorButton: typeof import('./src/components/SponsorButton.vue')['default']
    SubNav: typeof import('./src/components/SubNav.vue')['default']
    TextCopy: typeof import('./src/components/TextCopy.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    Tweet: typeof import('./src/components/Tweet.vue')['default']
    Unocss: typeof import('./src/components/icons/Unocss.vue')['default']
    ViteLogo: typeof import('./src/components/icons/ViteLogo.vue')['default']
    Vitest: typeof import('./src/components/icons/Vitest.vue')['default']
    VueDemi: typeof import('./src/components/icons/VueDemi.vue')['default']
    VueReactivity: typeof import('./src/components/icons/VueReactivity.vue')['default']
    VueUse: typeof import('./src/components/icons/VueUse.vue')['default']
    VueUseFn: typeof import('./src/components/slides/VueUseFn.vue')['default']
    WrapperDemo: typeof import('./src/components/WrapperDemo.vue')['default']
    WrapperPost: typeof import('./src/components/WrapperPost.vue')['default']
  }
}
